### PR TITLE
Remove ruby 2.x

### PR DESCRIPTION
**Pull request by NotMyFault**
jenkins.io has been migrated to ruby 3, and the plugin site doesn't depend on ruby at all.
I looked for repositories using this image to build and could find no trace of ruby 2 dependencies.

If there are no private repositories using this image and depending on ruby 2, we can drop 2.x here.

### CODE REVIEW

**Review by dduportal — COMMENTED** [review]
Side note: https://github.com/jenkins-infra/infra-reports is also using this image (https://github.com/jenkins-infra/infra-reports/blob/main/JenkinsAgentPodTemplate.yaml#L5) and requires Ruby 2.x as for today (Using Bundler 2.2.x: https://github.com/jenkins-infra/infra-reports/blob/main/fork-report/Gemfile.lock#L37 and https://github.com/jenkins-infra/infra-reports/blob/main/permissions-report/Gemfile.lock#L33).

Proposal: 
- LGTM to merge this PR, but we must mark it as a`breaking change`
- Let's switch infra-reports to Ruby 3.x (and then bump the image version on it) OR switch it to the packer-images Docker image (which has 2.6.x)

**Comment by dduportal** [comment]
Please note that Puppet still requires Ruby 2.x: that is the reason to keep it in the packer-images (ref. https://github.com/jenkins-infra/jenkins-infra/blob/production/Jenkinsfile#L5)

**Comment by NotMyFault** [comment]
> and requires Ruby 2.x as for today (Using Bundler 2.2.x: https://github.com/jenkins-infra/infra-reports/blob/main/fork-report/Gemfile.lock#L37

I created https://github.com/jenkins-infra/infra-reports/pull/53 to update ruby and node to the versions included in this docker image. 
To note, bundler 2 is not dedicated to ruby 2 or 3; there's no bundler 3 for ruby 3 if that's what you mean.

**Comment by dduportal** [comment]
> > and requires Ruby 2.x as for today (Using Bundler 2.2.x: https://github.com/jenkins-infra/infra-reports/blob/main/fork-report/Gemfile.lock#L37
> 
> I created [jenkins-infra/infra-reports#53](https://github.com/jenkins-infra/infra-reports/pull/53) to update ruby and node to the versions included in this docker image. To note, bundler 2 is not dedicated to ruby 2 or 3; there's no bundler 3 for ruby 3 if that's what you mean.

Nope, but bundler version is important due to default version packaged and assigned to default ruby version by asdf.

thanks for your PR on infra-reports: we can proceed here

**Review by dduportal — APPROVED** [review]

**Pull request merged**
